### ISSUE TITLE
Mobile Meta Tag

### ISSUE THREAD

**Issue by Mikeysax** [alysonpaige/firehoserepo#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by alysonpaige** [comment]
Looks like it's fixed, let me know what you think - thanks!

https://splurty-alyson-paige.herokuapp.com

**Comment by Mikeysax** [comment]
:+1: Nice job!
